export { default as Loader } from './Loader';
export { default as Button } from './Button';
export { default as Link } from './Link';
export { default as Navbar } from './Navbar';
export { default as Logo } from './Logo';
export { default as ButtonLink } from './ButtonLink';
export { default as Dialog } from './Dialog';
export { default as Img } from './Img';
export { default as Title } from './Title';
export { default as Card } from './Card';
export { default as Footer } from './Footer';
// export { default as Line } from './Line';
// export { default as IconCard } from './IconCard';
// export { default as IconCardLight } from './IconCardLight';
// export { default as BorderedCard } from './BorderedCard';
// export { default as Input } from './Input';
// export { default as List } from './List';
// export { default as TitleDashboard } from './TitleDashboard';
// export { default as Menu } from './Menu';
// export { default as Progress } from './Progress';
// export { default as TitledCard } from './TitledCard';
// export { default as SubList } from './SubList';
// export { default as FormDialog } from './FormDialog';
// export { default as VideoPlayer } from './VideoPlayer';
// export { default as Slider } from './Slider';

// // ========== admin
// export { default as AdminEditGroup } from './DataGridFormDialog/AdminEditGroup';
// export { default as AdminEditMentor } from './DataGridFormDialog/AdminEditMentor';
// export { default as AdminEditCourse } from './DataGridFormDialog/AdminEditCourse';
